### ISSUE TITLE
Gives problems with php 8.X

### ISSUE THREAD

**Issue by walterbe** [SFITCS/dokuwiki-plugin-dataau#1]
When changing php version 7.X to version 8.0.28 of a working docuwiki install version 2022-07-31a "Igor" it gives a lot of errors and made wiki not usable . 

The error is;

> dokuwiki\Exception\FatalException: Array and string offset access syntax with curly braces is no longer supported
> An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the dataau plugin.
> 
> More info has been written to the DokuWiki error log.

After changing back to the old php version, disabling this plugin (Structured Data-AU Plugin) and changing back too 8.X the wiki worked fine without errors.

**Comment by SFITCS** [comment]
Sorry Walter - it was a hasty hack that "just" worked with 7.x, and doesn't work at all with 8. I did look at what was required to make it work with 8.x and thought there might be a cleaner way of achieving the same outcome. I'll let you know if I come up with something (don't hold your breath - perpetually busy). Cheers
